# AngelaMos | 2026
# compose.dev.yml - Development compose with hot reload
# Connects to external MongoDB replica set via mongo-rs.yml network

services:
  backend:
    build:
      context: ./go-backend
      dockerfile: Dockerfile.dev
    container_name: oneisnun_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb_primary:27017,mongodb_secondary1:27017,mongodb_secondary2:27017/?replicaSet=rs0&authSource=admin
      - MONGODB_DATABASE=${MONGO_DB}
      - SQLITE_PATH=/app/data/dashboard.db
      - BACKUP_OUTPUT_DIR=/app/backups
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
    volumes:
      - ./go-backend:/app
      - backend_data:/app/data
      - backend_backups:/app/backups
    networks:
      - app_network
      - mongo_network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    develop:
      watch:
        - action: rebuild
          path: ./go-backend
          ignore:
            - "**/*.md"
            - "**/.*"

  frontend:
    build:
      context: ./react-scss
      dockerfile: Dockerfile.dev
    container_name: oneisnun_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8080
    volumes:
      - ./react-scss:/app
      - /app/node_modules
    networks:
      - app_network
    depends_on:
      backend:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./react-scss/src
          target: /app/src

volumes:
  backend_data:
    driver: local
  backend_backups:
    driver: local

networks:
  app_network:
    driver: bridge
  mongo_network:
    external: true
    name: oneisnun__mongo_network
