# one is presence

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_local
    restart: unless-stopped
    ports:
      - "1010:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - mongo_network

volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local

networks:
  mongo_network:
    driver: bridge
    name: oneisnun__mongo_network
